### ISSUE TITLE
Design Needed: Pushing Scalar Values to a Scalar List

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-admin-feedback#13]

**Comment by kuldar** [comment]
I think the simplest approach for now is to add a "new item" link under the context nav. When user clicks on it, we'd add a new item as the last row and focus on the input for user to fill out.

Since this new input could be either a text input, select, datepicker or textarea, we probably need to set a default value for enums and dates as well?

<img width="735" alt="scalarlists" src="https://user-images.githubusercontent.com/1710629/49580227-b12bc080-f94e-11e8-8170-d41d7dcd5e12.png">
