### ISSUE TITLE
Inline table editing

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-admin-feedback#19]
Additionally to editing data in the details section, it should be possible to inline edit values in table cells.

**Comment by kuldar** [comment]
Here's the current state of inline editing, open for feedback.

### Behaviours of different types of cells

- **ID** - unchangeable
- **String**, **Int**, **Float**, **JSON** - inline text input (possibly could expand vertically for multiline text edits)
- **Enum**, **Boolean** - dropdown to select between true/false or defined Enums
- **Datetime** - dropdown with datepicker
- **Single relation** - opens a modal with a table of nodes, allows to select one row (radio buttons)
- **Arrary** of **Strings**, **Ints**, **Floats**, **JSONs**, **Enums**, **Booleans**, **Datetimes** - opens a modal with a list of values and allows to edit, add/remove and rearragne the array items.
- **Array** of **relations** - opens a modal with a table of nodes, allows to select multiple (checkboxes)

**Keyboard behaviour** - upon clicking on a row, the clicked cell should gain a "focused" border as in the gif. This means that the user could also navigate the "focused" cell just by using the arrow keys and enter the "edit" state by hitting enter. When editing an array field, the "Add a new value" field in the modal should be automatically be "focused" (but not active), so that the user can add a new value by just hitting enter.

### Example of editing a String, Boolean and Single relation:
![inline-edit-2](https://user-images.githubusercontent.com/1710629/51029065-89ef9100-1595-11e9-8728-48538b751855.gif)

### Example of editing a String and an Array of Floats:
![inline-edit-1](https://user-images.githubusercontent.com/1710629/51029105-ae4b6d80-1595-11e9-8f90-a2d461c2207b.gif)

### Modal for 1:N relationship editing
![double click](https://user-images.githubusercontent.com/1710629/51029226-071b0600-1596-11e9-9f24-0207e267751f.png)
